AllCops:
  TargetRubyVersion:
    2.6.3
  Exclude:
    - bin/**/*
    - db/**/*
    - config/initializers/*
    - config/environments/*
    - vendor/**/*
    - config.ru
    - Rakefile
    - Guardfile

Documentation:
  Enabled: false
